apiVersion: v1
# Claim will be attached to our Pod config as what we need
kind: PersistentVolumeClaim
metadata:
    name: database-persistent-volume-claim
spec:
    # Access modes ====
    # ReadWriteOnce - Can be used by a single node only
    # ReadOnlyMany  - Multiple nodes can read from this
    # ReadWriteMany - Can be read and written to by many nodes
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            # Kubernetes must find a resource that has 2GB of space
            # whether it already exists (static volume) or has to be
            # created on the fly (dynamic volume)
            storage: 2Gi

    # Another possible option - we are not using
    # Specify the storage provider we want to use
    # storageClassName: xxxxxx
    # Possible storage options for above 
    # https://kubernetes.io/docs/concepts/storage/storage-classes

