apiVersion: apps/v1
kind: Deployment
metadata:
    name: server-deployment
spec:
    replicas: 3
    selector:
        matchLabels:
            component: server
    template:
        metadata:
            labels:
                component: server
        spec:
            containers:
                - name: server
                  # Spacing is VERY IMPORTANT!
                  # Is not a full tab indent, just two spaces
                  # After deploying to GCP, the "Indexes I have seen" did not work
                  # I used the TA's image below which worked fine???
                  #image: cygnetops/multi-server
                  # Per a Q/A post, I changed the pg version in the server package.json
                  # to 8.0.3 instead of ^8.0.3 which got it working so I can use my
                  # image!
                  image: mikenol/multi-server
                  ports:
                      - containerPort: 5000
                  env:
                      - name: REDIS_HOST
                        value: redis-cluster-ip-service
                      - name: REDIS_PORT
                        value: '6379'
                      - name: PGUSER
                        value: postgres
                      - name: PGHOST
                        value: postgres-cluster-ip-service
                      - name: PGPORT
                        value: '5432'
                      - name: PGDATABASE
                        value: postgres
                      - name: PGPASSWORD
                        # Get the secret key
                        valueFrom:
                            secretKeyRef:
                                # This is the name you gave the secret, not the env variable
                                name: pgpassword
                                # This is the the key for the key, value pair
                                key: PGPASSWORD
 